services:
  backend:
    build:
      context: ./Backend
    image: mafimashrafi/model_to_api-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app       
    command: uvicorn app:app --host 0.0.0.0 --port 8000  

  frontend:
    build:
      context: ./Frontend
    image: mafimashrafi/model_to_api-frontend:latest
    ports:
      - "8501:8501"
    command: streamlit run frontend.py --server.port 8501  
    depends_on:
      - backend